version: '3.5'

services:
  mockserver:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - LOG_LEVEL=warn
    volumes:
      - ./routes.json:/opt/routes.json